Db interface
allyourbasepair/allbase pull request #28
Opened 2022-04-19 20:41 UTC by TimothyStiles

Many people have suggested their DB backend of choice.

TBH I don't want to mess with SQL. Some people have interest in neo4j. I don't like any solutions right now so until I can find something that personally satisfies me I've created a basic interface that individuals can use to hook up there DB backend of choice to allbase.

There still is a lot to do interface design wise. Still finalizing structs, method signatures, etc and I will be actively working on this.

2022-04-20 14:03 UTC, Koeng101 requested changes
> a basic interface that individuals can use to hook up there DB backend of choice to allbase.

IMO this seems like the pathway to a hot mess of garbage. It also seems like you're thinking of databases as "key value store", which is not the way to think about relational databases. The structure of the data matters a lot for performance and maintenance overhead. 

I think it is much better for the project if you go figure out which database satisfies you, rather than trying to slap on a poorly thought out interface that we'll have to be tied to.

2022-04-25 18:30 UTC, TimothyStiles commented on db/db.go
> +	Query(query string) ([]map[string]string, error)
Yeah this is just a place holder generated by github co-pilot. Got a better suggestion? Could use generics or just a dedicated struct.

2022-04-25 18:31 UTC, TimothyStiles commented on db/db.go
> +	Delete(key string) error
auto-generated co-pilot place holder. Would probably just delete on a unique ID. Any other ideas?

2022-05-22 01:26 UTC, TimothyStiles commented
stale and no longer necessary. Closing.

2022-05-22 01:26 UTC, closed without merging